export const FETCH_JOURNALIST_DETAIL = "FETCH_JOURNALIST_DETAIL";
export const FETCH_JOURNALIST_DETAIL_SUCCESS =
  "FETCH_JOURNALIST_DETAIL_SUCCESS";
export const FETCH_JOURNALIST_DETAIL_ERROR = "FETCH_JOURNALIST_DETAIL_ERROR";
